build:
    build_starting:
        image: python:2
        commands:
            - echo "Beginning new build"
    run_tests:
      image: python:2-alpine
      commands:
          - pip install -r requirements.txt
          - python testing.py

publish:
    docker:
        repo: jgriff2/cicd_demoapp
        tag: latest
        username: jgriff2
        password: nopass123
        email: schizzy63@gmail.com

deploy:
    webhook:
        image: plugins/drone-webhook
        skip_verify: true
        method: POST
        auth:
            username: CICD1
            password: CICD1
        urls:
            - https://control.sandbox.imapex.io/marathon/v2/apps/class/jgriff2/restart?force=true

notify:
    spark:
        image: hpreston/drone-spark
        auth_token: MjNiZmVmZDUtZTU2NC00MWMzLWE4MDctNzk4NDJlODRjYzgxMWIxNGNiMjctYzcy
        roomId: Y2lzY29zcGFyazovL3VzL1JPT00vODVmMzAzNTAtMTQwNC0xMWU3LTkxZWQtNjMzYWE4Y2FkZDNj
